language: ruby
rvm:
  - 2.2.4
  - jruby-19mode
  - jruby-head
  - ruby-head
  - ree
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: true
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database odania_core_test'
  - psql -c 'create database odania_core_test' -U postgres
addons:
  code_climate:
    repo_token: 2b335554fb7a1f2c6b00f37eebda596c8b10fcd1717a8ee55dd449b60a21ac11
