json.id widget.id
json.site_id widget.site_id
json.user_id widget.user_id
json.language_id widget.language_id
json.template widget.template
json.name widget.name
json.content widget.content
json.created_at widget.created_at.to_i
json.updated_at widget.updated_at.to_i
